@catalogUrl = http://localhost:5222

###Test 1: Get Item Not Exists -> STT 404 ProblemDetails have traceId
GET {{catalogUrl}}/api/catalog/items/99999?api-version=1.0

###Test 2: Get Item Id < 0 -> STT 400 ProblemDetails have traceId
GET {{catalogUrl}}/api/catalog/items/-5?api-version=1.0

###Test 3: GET Item with true id (id = 1) -> STT 200 OK with data
GET {{catalogUrl}}/api/catalog/items/1?api-version=1.0